apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim-hadi-alireza
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "200Mi"
