apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    nodePort: 31221
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        resources:
          requests:
            memory: "400Mi"
            cpu: "0.2"
          limits:
            memory: "400Mi"
            cpu: "0.2"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: loghmeh
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-hadi-alireza
          mountPath: /var/lib/mysql
          subPath: hadi-alireza-mysql
      volumes:
      - name: mysql-persistent-storage-hadi-alireza
        persistentVolumeClaim:
          claimName: mysql-claim-hadi-alireza
